version: "3"
services:
  web:
    build: ./
    container_name: "lightning-pm"
#    user: "$USER_ID:$GROUP_ID"
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../../:/var/www
      - ${APACHE_LOGS_PATH}:/var/log/apache2
      - ${PHP_LOGS_PATH}:/var/log/php
    depends_on:
      - db
      - memcached

  db:
#    platform: linux/x86_64
    image: mysql:8.0.43
    restart: unless-stopped
    user: "$USER_ID:$GROUP_ID"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/db:/var/lib/mysql
      - ./data/files:/var/lib/mysql-files
      - ./data/tmp:/var/tmp
    expose:
      - 3306

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db

  memcached:
    image: memcached
    restart: unless-stopped
